# Prompt Evaluation Analysis

This notebook loads the results from the latest MLflow evaluation run and calculates metrics such as overall accuracy and failure rates per scorer.

In [1]:
import os
from pathlib import Path

import pandas as pd
import mlflow
from mlflow.tracking import MlflowClient

def find_project_root(start: Path) -> Path:
    """Find the project root by locating the evaluation/mlflow.db file."""
    current = start.resolve()
    candidates = [current, *current.parents]
    for candidate in candidates:
        if (candidate / "evaluation" / "mlflow.db").exists():
            return candidate
    return current

project_root = find_project_root(Path.cwd())
db_path = (project_root / "evaluation" / "mlflow.db").resolve()

print(f"Working directory: {Path.cwd()}")
print(f"Project root: {project_root}")
print(f"MLflow DB path: {db_path}")
print(f"DB exists: {db_path.exists()}")

Working directory: /home/phen/projects/customer-service-scheduling-bot/notebooks
Project root: /home/phen/projects/customer-service-scheduling-bot
MLflow DB path: /home/phen/projects/customer-service-scheduling-bot/evaluation/mlflow.db
DB exists: True

In [2]:
env_tracking_uri = os.getenv("MLFLOW_TRACKING_URI")

if env_tracking_uri and env_tracking_uri.startswith("sqlite:///") and not env_tracking_uri.startswith("sqlite:////"):
    # Convert sqlite:///relative/path.db to an absolute URI from project root.
    relative_part = env_tracking_uri.removeprefix("sqlite:///")
    resolved_db = (project_root / relative_part).resolve()
    tracking_uri = f"sqlite:///{resolved_db}"
elif env_tracking_uri:
    tracking_uri = env_tracking_uri
else:
    tracking_uri = f"sqlite:///{db_path}"

print(f"Using tracking URI: {tracking_uri}")

Using tracking URI: sqlite:////home/phen/projects/customer-service-scheduling-bot/evaluation/mlflow.db

In [3]:
mlflow.set_tracking_uri(tracking_uri)
client = MlflowClient()

print(f"Tracking URI: {tracking_uri}")
print("Available experiments:")
for exp in client.search_experiments():
    print(f"- id={exp.experiment_id}, name={exp.name}, stage={exp.lifecycle_stage}")

Tracking URI: sqlite:////home/phen/projects/customer-service-scheduling-bot/evaluation/mlflow.db
Available experiments:
- id=2, name=gateway/openai-o4-mini-endpoint, stage=active
- id=1, name=customer-service-bot, stage=active
- id=0, name=Default, stage=active

In [4]:
experiment_name = os.getenv("MLFLOW_EXPERIMENT_NAME", "customer-service-bot")
experiment = client.get_experiment_by_name(experiment_name)

if experiment is None:
    print(f"Experiment '{experiment_name}' was not found in the active tracking DB.")
    print("Available experiment names:")
    for exp in client.search_experiments():
        print(f"- {exp.name}")
else:
    print(f"Found experiment '{experiment.name}' with id={experiment.experiment_id}")
    experiment

Found experiment 'customer-service-bot' with id=1

In [5]:
if experiment is None:
    print("No experiment selected.")
else:
    print(f"Experiment ID: {experiment.experiment_id}")

Experiment ID: 1

In [6]:
# Fetch the latest full evaluation run
runs = client.search_runs(
    experiment_ids=[experiment.experiment_id],
    # filter_string="tags.mlflow.runName LIKE 'prompt-eval-full%'",
    order_by=["start_time DESC"],
    # max_results=1
)

In [7]:
from datetime import datetime

In [8]:

if not runs:
    print("No full evaluation runs found.")
else:
    latest_run = runs[0]
    print(f"Latest Run ID: {latest_run.info.run_id}")
    print(f"Run Name: {latest_run.data.tags.get('mlflow.runName')}")

    for run in runs[:-1]:
        if run.info.status == "FINISHED":
            print(f"Run name: {run.info.run_name}, Run ID: {run.info.run_id}, Status: {run.info.status}, Start Time: {datetime.fromtimestamp(run.info.start_time / 1000.0)}")   
        # print(f"Run ID: {run.info.run_id}, Name: {run.data.tags.get('mlflow.runName')}, Start Time: {run.info.start_time}")

Latest Run ID: de8ed242585b4c1eaab53030ca7f9e86
Run Name: omniscient-ram-469
Run name: omniscient-ram-469, Run ID: de8ed242585b4c1eaab53030ca7f9e86, Status: FINISHED, Start Time: 2026-07-24 21:55:29.365000
Run name: magnificent-crab-619, Run ID: 5879df51990c48218c0e672f964dc73a, Status: FINISHED, Start Time: 2026-07-24 21:55:00.590000
Run name: unique-crab-584, Run ID: 0209c2e6d4294abbb7a937705e1e718a, Status: FINISHED, Start Time: 2026-07-24 21:54:25.871000
Run name: upbeat-wolf-376, Run ID: 35819fe559ee4a5b9d1e091f8146c94b, Status: FINISHED, Start Time: 2026-07-24 21:53:50.330000
Run name: magnificent-mole-936, Run ID: 82801896915a4d7d9aa8cbb1f732b4ae, Status: FINISHED, Start Time: 2026-07-24 21:35:57.055000
Run name: useful-horse-56, Run ID: b0d8f94072c64d4e8ab7e3d46d52c3fb, Status: FINISHED, Start Time: 2026-07-24 21:35:51.199000
Run name: trusting-mink-798, Run ID: f424fd6e59364ecfa21bbc2e50927beb, Status: FINISHED, Start Time: 2026-07-24 21:35:45.422000
Run name: capable-fly-691, Run ID: 3440685ba7054ffd91c2374c757563ed, Status: FINISHED, Start Time: 2026-07-24 21:35:37.634000
Run name: handsome-goose-169, Run ID: 3c0712443bb849b6b5b0221e86069543, Status: FINISHED, Start Time: 2026-07-24 21:33:25.248000
Run name: bedecked-ape-978, Run ID: b6fbcd1504564a7c981bb135da86a7aa, Status: FINISHED, Start Time: 2026-07-24 21:33:17.037000
Run name: indecisive-bat-102, Run ID: 3802a701e0b949648091c535997c62dc, Status: FINISHED, Start Time: 2026-07-24 21:33:11.309000
Run name: upbeat-smelt-274, Run ID: ff6208914ed64af19ee119c882b50c4c, Status: FINISHED, Start Time: 2026-07-24 21:33:01.615000
Run name: youthful-slug-91, Run ID: 0d068ee2b5aa43ab83cea484a47cb5c1, Status: FINISHED, Start Time: 2026-07-24 21:22:36.705000
Run name: nosy-crab-210, Run ID: 9a02b1c69d4349bbb52256277288c7c2, Status: FINISHED, Start Time: 2026-07-24 18:46:00.212000
Run name: secretive-cod-237, Run ID: 2a56f9a5ab6e408089b53a6855aa054a, Status: FINISHED, Start Time: 2026-07-24 18:06:20.413000
Run name: ambitious-calf-594, Run ID: 929c653f0d8a44da82d0443f9b41166b, Status: FINISHED, Start Time: 2026-07-23 17:54:40.219000
Run name: exultant-colt-941, Run ID: cd3987b818a74463a0d85e88c4ee0bf7, Status: FINISHED, Start Time: 2026-07-23 17:21:33.606000
Run name: sincere-whale-245, Run ID: 80e1e0fbed8544e38849e4950c4be95d, Status: FINISHED, Start Time: 2026-07-23 16:40:55.397000
Run name: gregarious-tern-951, Run ID: ab72e6872faf47a4999e35814cbd7735, Status: FINISHED, Start Time: 2026-07-23 13:44:23.914000
Run name: stylish-koi-787, Run ID: 9706a71f7376455ba5a67580bae0f8f6, Status: FINISHED, Start Time: 2026-07-23 13:39:10.778000
Run name: glamorous-lamb-684, Run ID: b007fcf1a07b49b28490399fd91660e4, Status: FINISHED, Start Time: 2026-07-23 13:36:28.698000

In [9]:
slct_run_names = [
    'omniscient-ram-469',
    'magnificent-crab-619',
    'unique-crab-584',
    'upbeat-wolf-376'
]

slct_runs = [run for run in runs if run.info.run_name in slct_run_names]
len(slct_runs)

4

In [10]:
runs[0].__dict__.keys()

dict_keys(['_info', '_data', '_inputs', '_outputs'])

In [11]:
runs[0]._info

<RunInfo: artifact_uri='/home/phen/projects/customer-service-scheduling-bot/mlruns/1/de8ed242585b4c1eaab53030ca7f9e86/artifacts', end_time=1784940944978, experiment_id='1', lifecycle_stage='active', run_id='de8ed242585b4c1eaab53030ca7f9e86', run_name='omniscient-ram-469', start_time=1784940929365, status='FINISHED', user_id='phen'>

In [12]:
runs[0]._data

<RunData: metrics={'tool_match': 1.0}, params={}, tags={'mlflow.runName': 'omniscient-ram-469',
 'mlflow.runType': 'genai_evaluate',
 'mlflow.source.git.branch': 'master',
 'mlflow.source.git.commit': 'fff919dbc9dcea4eae4895e58b5fa3b07350ecb9',
 'mlflow.source.git.repoURL': 'https://github.com/phnv/customer-service-scheduling-bot.git',
 'mlflow.source.name': 'scripts/run_evaluation.py',
 'mlflow.source.type': 'LOCAL',
 'mlflow.user': 'phen'}>

In [13]:
runs[0]._inputs

<RunInputs: dataset_inputs=[<DatasetInput: dataset=<Dataset: digest='e5cbba12', name='dataset', profile='{"num_rows": 8, "num_elements": 72}', schema=None, source=('{"tags": {"mlflow.user": "phen", "mlflow.source.name": '
 '"scripts/run_evaluation.py", "mlflow.source.type": "LOCAL", '
 '"mlflow.source.git.commit": "fff919dbc9dcea4eae4895e58b5fa3b07350ecb9", '
 '"mlflow.source.git.branch": "master", "mlflow.source.git.repoURL": '
 '"https://github.com/phnv/customer-service-scheduling-bot.git"}}'), source_type='code'>, tags=[]>], model_inputs=[]>

In [14]:
runs[0]._outputs

## Load Evaluation Traces from DB

Instead of relying on the `eval_results_table` artifact, we can query traces directly from the MLflow database.
We will search for traces in the experiment, examine their `assessments` for scorer failures, and collect them for manual inspection.

In [15]:
import pandas as pd

traces_df = []

try:
    # Fetch traces for the experiment directly from MLflow DB
    # Note: Experiment ID '1' is MLflow Demo which has the failed assessments.
    for run in slct_runs: 
        traces = mlflow.search_traces(experiment_ids=['1'], max_results=200, run_id=run.info.run_id)
        traces_df.append(traces)
        if traces is not None:
            print(f"Loaded {len(traces)} traces from MLflow DB for run {run.info.run_name} (ID: {run.info.run_id}).")
        else:
            print(f"No traces found for run {run.info.run_name} (ID: {run.info.run_id}).")
except Exception as e:
    print(f"Failed to load traces from MLflow DB: {e}")
    
# print(f"Loaded {len(traces_df)} traces from MLflow DB.")
traces_df = pd.concat(traces_df, ignore_index=True)

/tmp/ipykernel_46604/51999519.py:9: FutureWarning: Parameter 'experiment_ids' is deprecated. Please use 'locations' instead.
  traces = mlflow.search_traces(experiment_ids=['1'], max_results=200, run_id=run.info.run_id)

Loaded 8 traces from MLflow DB for run omniscient-ram-469 (ID: de8ed242585b4c1eaab53030ca7f9e86).
Loaded 13 traces from MLflow DB for run magnificent-crab-619 (ID: 5879df51990c48218c0e672f964dc73a).
Loaded 12 traces from MLflow DB for run unique-crab-584 (ID: 0209c2e6d4294abbb7a937705e1e718a).
Loaded 17 traces from MLflow DB for run upbeat-wolf-376 (ID: 35819fe559ee4a5b9d1e091f8146c94b).

In [16]:
traces_df['assessments'][0]

[{'assessment_id': 'a-769085aa8f8e44d0b35c0c3431f116da',
  'assessment_name': 'ExpectationsMet',
  'trace_id': 'tr-55cd4201b5bcb69b6392472837740bc9',
  'span_id': 'a42bba0a09bfbf77',
  'source': {'source_type': 'LLM_JUDGE', 'source_id': 'openai:/gpt-4o-mini'},
  'create_time': '2026-07-25T00:55:42.131Z',
  'last_update_time': '2026-07-25T00:55:42.131Z',
  'feedback': {'value': 'yes'},
  'rationale': "The response correctly indicates that the agent called the 'search_faq_tool' as part of retrieving information. The output confirms that the tool was used by listing it under the '=== TOOLS ===' section. Furthermore, the information provided in the '=== RESPONSE ===' section directly falls under the expected output of the tool usage, thus fulfilling the criteria outlined in the expectations.",
  'metadata': {'mlflow.assessment.judgeCost': '0.0001578',
   'mlflow.assessment.sourceRunId': 'de8ed242585b4c1eaab53030ca7f9e86',
   'guideline': '\n    You are evaluating whether an agent met specific expectations.\n    \n    Given the expectation criteria: {{ expectations }}\n    \n    Extract the text under the === RESPONSE === section from the output {{ outputs }}.\n    Determine if this response successfully fulfills the provided expectations.\n    \n    Return "yes" if the expectations are met, "no" if they are not.\n    ',
   'mlflow.assessment.judgeOutputTokens': '84',
   'mlflow.assessment.judgeInputTokens': '716'},
  'valid': True},
 {'assessment_id': 'a-06523ad92e7340558e12dbcacf7d7214',
  'assessment_name': 'Faithfulness',
  'trace_id': 'tr-55cd4201b5bcb69b6392472837740bc9',
  'span_id': 'a42bba0a09bfbf77',
  'source': {'source_type': 'LLM_JUDGE', 'source_id': 'openai:/gpt-4o-mini'},
  'create_time': '2026-07-25T00:55:42.200Z',
  'last_update_time': '2026-07-25T00:55:42.200Z',
  'feedback': {'value': 'yes'},
  'rationale': 'The RESPONSE accurately reflects the information presented in the CONTEXT, specifically Document 3, which lists the same medical specialties offered at the clinic. There are no discrepancies or additional claims made in the RESPONSE that are not supported by the CONTEXT.',
  'metadata': {'mlflow.assessment.judgeCost': '0.00014295',
   'mlflow.assessment.sourceRunId': 'de8ed242585b4c1eaab53030ca7f9e86',
   'guideline': '\n    You are evaluating whether an agent\'s response is faithful to the provided context.\n    \n    From the output {{ outputs }}, extract two sections:\n    1. The text under === CONTEXT ===\n    2. The text under === RESPONSE ===\n    \n    Determine if the information in the RESPONSE is completely supported by and grounded in the CONTEXT.\n    If the RESPONSE contains claims, facts, or data not present in the CONTEXT, return "no".\n    If the RESPONSE is entirely supported by the CONTEXT, return "yes".\n    ',
   'mlflow.assessment.judgeOutputTokens': '57',
   'mlflow.assessment.judgeInputTokens': '725'},
  'valid': True},
 {'assessment_id': 'a-4791a464e54445b8a687b294c83d98de',
  'assessment_name': 'ResponseQuality',
  'trace_id': 'tr-55cd4201b5bcb69b6392472837740bc9',
  'span_id': 'a42bba0a09bfbf77',
  'source': {'source_type': 'LLM_JUDGE', 'source_id': 'openai:/gpt-4o-mini'},
  'create_time': '2026-07-25T00:55:44.580Z',
  'last_update_time': '2026-07-25T00:55:44.580Z',
  'feedback': {'value': 'yes'},
  'rationale': 'The response clearly outlines the specialties offered by the clinic, which is directly relevant to the likely user query regarding available consultations. It is coherent and maintains a professional tone throughout. The information provided is helpful and straightforward, allowing the user to quickly understand the range of services without any confusion.',
  'metadata': {'mlflow.assessment.judgeCost': '0.00014429999999999998',
   'mlflow.assessment.sourceRunId': 'de8ed242585b4c1eaab53030ca7f9e86',
   'guideline': '\n    You are evaluating the quality of an agent\'s response.\n    \n    Extract the text under the === RESPONSE === section from the output {{ outputs }}.\n    Evaluate the overall quality of this response based on:\n    1. Clarity and coherence\n    2. Professionalism and tone\n    3. Helpfulness to the user\n    \n    Return "yes" if the response is of high quality, "no" otherwise.\n    ',
   'mlflow.assessment.judgeOutputTokens': '65',
   'mlflow.assessment.judgeInputTokens': '702'},
  'valid': True},
 {'assessment_id': 'a-622b1a30759d4264b13da820e69f1369',
  'assessment_name': 'criteria',
  'trace_id': 'tr-55cd4201b5bcb69b6392472837740bc9',
  'span_id': 'a42bba0a09bfbf77',
  'source': {'source_type': 'HUMAN', 'source_id': 'phen'},
  'create_time': '2026-07-25T00:55:44.582Z',
  'last_update_time': '2026-07-25T00:55:44.582Z',
  'expectation': {'value': 'Calls search_faq_tool.'},
  'metadata': {'mlflow.assessment.sourceRunId': 'de8ed242585b4c1eaab53030ca7f9e86'},
  'valid': True},
 {'assessment_id': 'a-1bd0908374b341dbb470b2c32f36e91e',
  'assessment_name': 'expected_tools',
  'trace_id': 'tr-55cd4201b5bcb69b6392472837740bc9',
  'span_id': 'a42bba0a09bfbf77',
  'source': {'source_type': 'HUMAN', 'source_id': 'phen'},
  'create_time': '2026-07-25T00:55:44.582Z',
  'last_update_time': '2026-07-25T00:55:44.582Z',
  'expectation': {'serialized_value': {'serialization_format': 'JSON_FORMAT',
    'value': '["search_faq_tool"]'}},
  'metadata': {'mlflow.assessment.sourceRunId': 'de8ed242585b4c1eaab53030ca7f9e86'},
  'valid': True}]

In [17]:
run.info.run_id

'35819fe559ee4a5b9d1e091f8146c94b'

## Traces Analysis (both Failed and ok)

Filter the traces to find those whose assessments failed (either due to a scorer error or a 'no' value).

In [18]:


# traces_df['spans'][0]
traces_df['assessments'][0]

[{'assessment_id': 'a-769085aa8f8e44d0b35c0c3431f116da',
  'assessment_name': 'ExpectationsMet',
  'trace_id': 'tr-55cd4201b5bcb69b6392472837740bc9',
  'span_id': 'a42bba0a09bfbf77',
  'source': {'source_type': 'LLM_JUDGE', 'source_id': 'openai:/gpt-4o-mini'},
  'create_time': '2026-07-25T00:55:42.131Z',
  'last_update_time': '2026-07-25T00:55:42.131Z',
  'feedback': {'value': 'yes'},
  'rationale': "The response correctly indicates that the agent called the 'search_faq_tool' as part of retrieving information. The output confirms that the tool was used by listing it under the '=== TOOLS ===' section. Furthermore, the information provided in the '=== RESPONSE ===' section directly falls under the expected output of the tool usage, thus fulfilling the criteria outlined in the expectations.",
  'metadata': {'mlflow.assessment.judgeCost': '0.0001578',
   'mlflow.assessment.sourceRunId': 'de8ed242585b4c1eaab53030ca7f9e86',
   'guideline': '\n    You are evaluating whether an agent met specific expectations.\n    \n    Given the expectation criteria: {{ expectations }}\n    \n    Extract the text under the === RESPONSE === section from the output {{ outputs }}.\n    Determine if this response successfully fulfills the provided expectations.\n    \n    Return "yes" if the expectations are met, "no" if they are not.\n    ',
   'mlflow.assessment.judgeOutputTokens': '84',
   'mlflow.assessment.judgeInputTokens': '716'},
  'valid': True},
 {'assessment_id': 'a-06523ad92e7340558e12dbcacf7d7214',
  'assessment_name': 'Faithfulness',
  'trace_id': 'tr-55cd4201b5bcb69b6392472837740bc9',
  'span_id': 'a42bba0a09bfbf77',
  'source': {'source_type': 'LLM_JUDGE', 'source_id': 'openai:/gpt-4o-mini'},
  'create_time': '2026-07-25T00:55:42.200Z',
  'last_update_time': '2026-07-25T00:55:42.200Z',
  'feedback': {'value': 'yes'},
  'rationale': 'The RESPONSE accurately reflects the information presented in the CONTEXT, specifically Document 3, which lists the same medical specialties offered at the clinic. There are no discrepancies or additional claims made in the RESPONSE that are not supported by the CONTEXT.',
  'metadata': {'mlflow.assessment.judgeCost': '0.00014295',
   'mlflow.assessment.sourceRunId': 'de8ed242585b4c1eaab53030ca7f9e86',
   'guideline': '\n    You are evaluating whether an agent\'s response is faithful to the provided context.\n    \n    From the output {{ outputs }}, extract two sections:\n    1. The text under === CONTEXT ===\n    2. The text under === RESPONSE ===\n    \n    Determine if the information in the RESPONSE is completely supported by and grounded in the CONTEXT.\n    If the RESPONSE contains claims, facts, or data not present in the CONTEXT, return "no".\n    If the RESPONSE is entirely supported by the CONTEXT, return "yes".\n    ',
   'mlflow.assessment.judgeOutputTokens': '57',
   'mlflow.assessment.judgeInputTokens': '725'},
  'valid': True},
 {'assessment_id': 'a-4791a464e54445b8a687b294c83d98de',
  'assessment_name': 'ResponseQuality',
  'trace_id': 'tr-55cd4201b5bcb69b6392472837740bc9',
  'span_id': 'a42bba0a09bfbf77',
  'source': {'source_type': 'LLM_JUDGE', 'source_id': 'openai:/gpt-4o-mini'},
  'create_time': '2026-07-25T00:55:44.580Z',
  'last_update_time': '2026-07-25T00:55:44.580Z',
  'feedback': {'value': 'yes'},
  'rationale': 'The response clearly outlines the specialties offered by the clinic, which is directly relevant to the likely user query regarding available consultations. It is coherent and maintains a professional tone throughout. The information provided is helpful and straightforward, allowing the user to quickly understand the range of services without any confusion.',
  'metadata': {'mlflow.assessment.judgeCost': '0.00014429999999999998',
   'mlflow.assessment.sourceRunId': 'de8ed242585b4c1eaab53030ca7f9e86',
   'guideline': '\n    You are evaluating the quality of an agent\'s response.\n    \n    Extract the text under the === RESPONSE === section from the output {{ outputs }}.\n    Evaluate the overall quality of this response based on:\n    1. Clarity and coherence\n    2. Professionalism and tone\n    3. Helpfulness to the user\n    \n    Return "yes" if the response is of high quality, "no" otherwise.\n    ',
   'mlflow.assessment.judgeOutputTokens': '65',
   'mlflow.assessment.judgeInputTokens': '702'},
  'valid': True},
 {'assessment_id': 'a-622b1a30759d4264b13da820e69f1369',
  'assessment_name': 'criteria',
  'trace_id': 'tr-55cd4201b5bcb69b6392472837740bc9',
  'span_id': 'a42bba0a09bfbf77',
  'source': {'source_type': 'HUMAN', 'source_id': 'phen'},
  'create_time': '2026-07-25T00:55:44.582Z',
  'last_update_time': '2026-07-25T00:55:44.582Z',
  'expectation': {'value': 'Calls search_faq_tool.'},
  'metadata': {'mlflow.assessment.sourceRunId': 'de8ed242585b4c1eaab53030ca7f9e86'},
  'valid': True},
 {'assessment_id': 'a-1bd0908374b341dbb470b2c32f36e91e',
  'assessment_name': 'expected_tools',
  'trace_id': 'tr-55cd4201b5bcb69b6392472837740bc9',
  'span_id': 'a42bba0a09bfbf77',
  'source': {'source_type': 'HUMAN', 'source_id': 'phen'},
  'create_time': '2026-07-25T00:55:44.582Z',
  'last_update_time': '2026-07-25T00:55:44.582Z',
  'expectation': {'serialized_value': {'serialization_format': 'JSON_FORMAT',
    'value': '["search_faq_tool"]'}},
  'metadata': {'mlflow.assessment.sourceRunId': 'de8ed242585b4c1eaab53030ca7f9e86'},
  'valid': True}]

In [19]:
# @AGENT: adapt from this point forward 

all_assessments = []
failed_traces = []

if traces_df is not None and not traces_df.empty:
    for idx, row in traces_df.iterrows():
        assessments = row.get('assessments', [])
        
        has_trace_failure = False
        failure_reasons = []
        failure_reasons_2 = []
        
        if not assessments:
            all_assessments.append({
                'trace_id': row.get('trace_id'),
                'request': row.get('request'),
                'response': row.get('response'),
                'scorer_name': None,
                'has_failure': False,
                'error_code': None,
                'error_message': None,
                'rationale': None,
                'expectation': None,
                'feedback_value': None
            })
            continue
            
        for assessment in assessments:
            if assessment.get('source', {}).get('source_type') == 'HUMAN':
                continue
            feedback = assessment.get('feedback', {})
            error_code = assessment.get('error_code')
            error_message = assessment.get('error_message')
            rationale = assessment.get('rationale')
            expectation = assessment.get('expectation', {}).get('value') if isinstance(assessment.get('expectation'), dict) else None
            val = feedback.get('value')
            
            scorer_name = assessment.get('assessment_name', 'UnknownScorer')
            
            has_failure = False
            if error_code is not None or error_message is not None:
                has_failure = True
                failure_reasons.append(f"{scorer_name} Error: {error_code} - {error_message}")
                failure_reasons_2.append({'scorer_name': scorer_name, 'error_reason': error_message or str(error_code), 'rationale': rationale, 'expectation': expectation})
            elif val is None or str(val).lower() != 'yes':
                has_failure = True
                failure_reasons.append(f"{scorer_name} Failed: {rationale}")
                failure_reasons_2.append({'scorer_name': scorer_name, 'error_reason': 'no error rationale', 'rationale': rationale, 'expectation': expectation})
                
            if has_failure:
                has_trace_failure = True
                
            all_assessments.append({
                'trace_id': row.get('trace_id'),
                'request': row.get('request'),
                'response': row.get('response'),
                'scorer_name': scorer_name,
                'has_failure': has_failure,
                'error_code': error_code,
                'error_message': error_message,
                'rationale': rationale,
                'expectation': expectation,
                'feedback_value': val
            })
            
        if has_trace_failure:
            failed_traces.append({
                'trace_id': row.get('trace_id'),
                'request': row.get('request'),
                'response': row.get('response'),
                'reasons': " | ".join(failure_reasons),
                'reasons_list': failure_reasons_2
            })
            
    all_traces_df = pd.DataFrame(all_assessments)
    print(f"Extracted {len(all_traces_df)} assessments from {len(traces_df)} traces.")
    print(f"Found {len(failed_traces)} failed or errored traces.")
else:
    print("No traces loaded.")
    all_traces_df = pd.DataFrame()

Extracted 150 assessments from 50 traces.
Found 43 failed or errored traces.

In [20]:
all_traces_df.head()

,trace_id,request,response,scorer_name,has_failure,error_code,error_message,rationale,expectation,feedback_value
0,tr-55cd4201b5bcb69b6392472837740bc9,{'user_message': 'What specialties do you offe...,"=== INTENT ===\nfaq\n\n=== TOOLS ===\n[""search...",ExpectationsMet,False,None,None,The response correctly indicates that the agen...,None,yes
1,tr-55cd4201b5bcb69b6392472837740bc9,{'user_message': 'What specialties do you offe...,"=== INTENT ===\nfaq\n\n=== TOOLS ===\n[""search...",Faithfulness,False,None,None,The RESPONSE accurately reflects the informati...,None,yes
2,tr-55cd4201b5bcb69b6392472837740bc9,{'user_message': 'What specialties do you offe...,"=== INTENT ===\nfaq\n\n=== TOOLS ===\n[""search...",ResponseQuality,False,None,None,The response clearly outlines the specialties ...,None,yes
3,tr-34265d10b81c4bb4a480bc37980fbfc4,{'user_message': 'What happens if I'm late to ...,"=== INTENT ===\nfaq\n\n=== TOOLS ===\n[""search...",ExpectationsMet,False,None,None,The response successfully meets the expectatio...,None,yes
4,tr-34265d10b81c4bb4a480bc37980fbfc4,{'user_message': 'What happens if I'm late to ...,"=== INTENT ===\nfaq\n\n=== TOOLS ===\n[""search...",Faithfulness,False,None,None,The RESPONSE accurately reflects the informati...,None,yes

In [ ]:
failurall_traces_df[all_traces_df['has_failure'] == True].head()

,trace_id,request,response,scorer_name,has_failure,error_code,error_message,rationale,expectation,feedback_value
7,tr-64bfeb7e9224be6dffcaa339a9aed1d9,"{'user_message': 'I have a headache, what medi...",=== INTENT ===\nescalation\n\n=== TOOLS ===\n[...,Faithfulness,True,None,None,"The CONTEXT is empty, providing no specific in...",None,no
9,tr-1ea5370a2fb844d649e0d223ac46be2b,{'user_message': 'What should I do if my arm h...,=== INTENT ===\nescalation\n\n=== TOOLS ===\n[...,ExpectationsMet,True,None,None,The response does not address medical advice o...,None,no
10,tr-1ea5370a2fb844d649e0d223ac46be2b,{'user_message': 'What should I do if my arm h...,=== INTENT ===\nescalation\n\n=== TOOLS ===\n[...,Faithfulness,True,None,None,"The CONTEXT is empty, which means there are no...",None,no
12,tr-ca34320f35072d86109da83f05a616f4,{'user_message': 'Can I book an appointment fo...,=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,ExpectationsMet,True,None,None,The response does not directly handle the book...,None,no
13,tr-ca34320f35072d86109da83f05a616f4,{'user_message': 'Can I book an appointment fo...,=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,Faithfulness,True,None,None,"The CONTEXT is empty (indicated by """"), which ...",None,no

In [25]:
all_traces_df[all_traces_df['scorer_name'] == 'criteria']

,trace_id,request,response,scorer_name,has_failure,error_code,error_message,rationale,expectation,feedback_value
3,tr-55cd4201b5bcb69b6392472837740bc9,{'user_message': 'What specialties do you offe...,"=== INTENT ===\nfaq\n\n=== TOOLS ===\n[""search...",criteria,True,None,None,None,Calls search_faq_tool.,None
8,tr-34265d10b81c4bb4a480bc37980fbfc4,{'user_message': 'What happens if I'm late to ...,"=== INTENT ===\nfaq\n\n=== TOOLS ===\n[""search...",criteria,True,None,None,None,Calls search_faq_tool.,None
13,tr-64bfeb7e9224be6dffcaa339a9aed1d9,"{'user_message': 'I have a headache, what medi...",=== INTENT ===\nescalation\n\n=== TOOLS ===\n[...,criteria,True,None,None,None,Does NOT provide medical advice.,None
17,tr-1ea5370a2fb844d649e0d223ac46be2b,{'user_message': 'What should I do if my arm h...,=== INTENT ===\nescalation\n\n=== TOOLS ===\n[...,criteria,True,None,None,None,Does NOT provide medical advice. Recommends co...,None
21,tr-ca34320f35072d86109da83f05a616f4,{'user_message': 'Can I book an appointment fo...,=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,criteria,True,None,None,None,Handles booking directly.,None
25,tr-42f02296b92616f5c5176e9047770d78,"{'user_message': 'Do you accept Medicare?', 'c...","=== INTENT ===\nfaq\n\n=== TOOLS ===\n[""search...",criteria,True,None,None,None,Calls search_faq_tool.,None
30,tr-e4551c2c462a0aea39df6307d49844ea,{'user_message': 'Do you accept Blue Cross ins...,"=== INTENT ===\nfaq\n\n=== TOOLS ===\n[""search...",criteria,True,None,None,None,Calls search_faq_tool.,None
35,tr-b6d1e906f83fa28b87870d536e70375d,{'user_message': 'How much does a dermatology ...,"=== INTENT ===\nfaq\n\n=== TOOLS ===\n[""search...",criteria,True,None,None,None,Calls search_services_tool.,None
40,tr-7d7a660d69ca8dc47bc4d76865e3a3fa,{'user_message': 'The 10am slot with Dr. Silva...,=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,criteria,True,None,None,None,Asks for explicit confirmation BEFORE calling ...,None
45,tr-943f3e2dc62ff8c7e751a862e78bb219,{'user_message': 'Can I reschedule my appointm...,=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,criteria,True,None,None,None,Uses reschedule_appointment_tool.,None
50,tr-b5fa726883ce28023b584ce73bcb6b29,{'user_message': '[System Event: Payment Expir...,=== INTENT ===\nescalation\n\n=== TOOLS ===\n[...,criteria,True,None,None,None,Acknowledges that the payment expired and the ...,None
54,tr-76b96b6342ab713aa946de49154ec572,"{'user_message': 'Yes, that's correct.', 'conv...",=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,criteria,True,None,None,None,Calls reserve_slot_tool.,None
59,tr-1496b12efceaa9bed4e685388f617a4b,"{'user_message': 'I need an endocrinologist.',...",=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,criteria,True,None,None,None,Calls check_availability_tool.,None
64,tr-c0a6294e652f23edb742847157d9a432,{'user_message': 'Do you have anything next Tu...,=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,criteria,True,None,None,None,Calls check_availability_tool.,None
69,tr-78b19bcae9b58313d1337394292d06e5,{'user_message': 'I need to reschedule my Thur...,=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,criteria,True,None,None,None,Uses reschedule_appointment_tool.,None
74,tr-ca7b36d19980877e0f8b1169e6caef46,{'user_message': 'I want to cancel my reservat...,=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,criteria,True,None,None,None,Calls cancel_appointment_tool (or cancel_reser...,None
79,tr-a41a953b4158022c3745efede3b3d91e,"{'user_message': 'Yes, please book it.', 'conv...",=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,criteria,True,None,None,None,Calls reserve_slot_tool.,None
84,tr-c65bdad9215445eb9e7606476489bcc6,{'user_message': 'Do you have any availability...,=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,criteria,True,None,None,None,Calls check_availability_tool with specialty='...,None
89,tr-38ab56933e3e73237d892ca388622344,{'user_message': 'I want the 9am slot with Dr....,=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,criteria,True,None,None,None,Asks for explicit confirmation of the 9am slot...,None
93,tr-10ff5c1dd64c8464cafcac9280a44077,{'user_message': '[System Event: Payment Confi...,=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,criteria,True,None,None,None,Acknowledges payment. Does NOT call tools.,None
97,tr-3b27012e509572089fe4563055f22d95,{'user_message': 'I need to cancel my appointm...,=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,criteria,True,None,None,None,Calls cancel_appointment_tool.,None
102,tr-b181330d66dbcc3ac372b5c5b5d6f2c1,{'user_message': 'The appointment is for my da...,=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,criteria,True,None,None,None,Calls select_patient_tool with Emma's patient_id.,None
107,tr-d38fc82df5003064364c83b4f2090a60,"{'user_message': 'My number is 555-9999, but I...","=== INTENT ===\nbooking\n\n=== TOOLS ===\n[""fi...",criteria,True,None,None,None,"Calls find_contact_tool, then asks for new use...",None
112,tr-340c4aa9131465c26cf020a9a1631289,"{'user_message': 'Wait, I need to update my em...",=== INTENT ===\nescalation\n\n=== TOOLS ===\n[...,criteria,True,None,None,None,"Escalates to a human agent, as self-service da...",None
116,tr-8f1a48437362cf0f5a498f084c01368c,"{'user_message': 'Actually, my phone number is...",=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,criteria,True,None,None,None,Does NOT call update_contact_tool. Escalates.,None
120,tr-d8d6498c64d3c997196c82ec4226601a,"{'user_message': 'Actually, can you book this ...","=== INTENT ===\nbooking\n\n=== TOOLS ===\n[""fi...",criteria,True,None,None,None,Handles patient switching.,None
124,tr-d73da6212fcd661a480ef511392713c0,{'user_message': 'My phone number is +15550001...,"=== INTENT ===\nbooking\n\n=== TOOLS ===\n[""fi...",criteria,True,None,None,None,Calls find_contact_tool.,None
129,tr-1ee1c4ec934b7dbc80c6da02089b65b2,"{'user_message': 'It's for my son, Michael.', ...","=== INTENT ===\nbooking\n\n=== TOOLS ===\n[""fi...",criteria,True,None,None,None,Calls select_patient_tool with Michael's patie...,None
134,tr-9dc3fdf427eb449a5d4b567b2689e33f,{'user_message': 'I don't have a phone number....,=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,criteria,True,None,None,None,Asks for email address or another form of iden...,None
138,tr-c557aa4f09d26229d17bb8654f2f8fe7,"{'user_message': 'I forgot my patient ID.', 'c...",=== INTENT ===\nescalation\n\n=== TOOLS ===\n[...,criteria,True,None,None,None,Proactively asks for other identifiers like fu...,None
142,tr-c7e177656754668be5943bbe3957e84d,"{'user_message': 'Hi.', 'conversation_history'...",=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,criteria,True,None,None,None,Reception proactively asks for contact identif...,None
146,tr-4c3f46740884f1da63a8c04b9bc764ea,"{'user_message': 'My name is Jane Smith, +1444...","=== INTENT ===\nbooking\n\n=== TOOLS ===\n[""fi...",criteria,True,None,None,None,Calls find_contact_tool.,None
151,tr-b2e57f242da990b34745523ce2fe937e,"{'user_message': 'Hi, I'd like to book an appo...",=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,criteria,True,None,None,None,Proactively asks for contact information.,None
155,tr-195417a545abac6a9ba64d3985e3b2ac,{'user_message': 'This is ridiculous! I've bee...,=== INTENT ===\nescalation\n\n=== TOOLS ===\n[...,criteria,True,None,None,None,Routes to escalation intent.,None
160,tr-84fdb216699085e18edfa06489b875fb,"{'user_message': 'Where are you located?', 'co...","=== INTENT ===\nfaq\n\n=== TOOLS ===\n[""search...",criteria,True,None,None,None,Routes to faq intent.,None
165,tr-e2912f6141dfe9e3e8fcd2ca42f77e2d,{'user_message': 'Can I get my medical records...,"=== INTENT ===\nfaq\n\n=== TOOLS ===\n[""search...",criteria,True,None,None,None,Routes to escalation intent.,None
170,tr-68ab592bc43a2cc0e6818cbbf5722a04,"{'user_message': 'Is telehealth available?', '...","=== INTENT ===\nfaq\n\n=== TOOLS ===\n[""search...",criteria,True,None,None,None,Routes to faq intent.,None
175,tr-c5ee6289b5a76e77a9f5b6c6a8d0d06f,"{'user_message': 'Cardiology.', 'conversation_...",=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,criteria,True,None,None,None,Routes to booking intent.,None
180,tr-d0915f9247492f67948022fb8281d8d2,{'user_message': 'Who is the best doctor for b...,"=== INTENT ===\nfaq\n\n=== TOOLS ===\n[""search...",criteria,True,None,None,None,Routes to faq intent.,None
185,tr-b6b48604c9ba50091031ec195632cf0d,"{'user_message': 'Actually, my phone number is...",=== INTENT ===\nescalation\n\n=== TOOLS ===\n[...,criteria,True,None,None,None,Routes to escalation intent.,None
190,tr-d20d3c24519db8a09f31eb3d1aad1013,{'user_message': 'Can I add a dependent to my ...,"=== INTENT ===\nfaq\n\n=== TOOLS ===\n[""search...",criteria,True,None,None,None,Routes to escalation intent.,None
195,tr-f22c6f58c35eb240cdd6a7bce976dbaf,"{'user_message': 'Actually, how much does a de...","=== INTENT ===\nfaq\n\n=== TOOLS ===\n[""search...",criteria,True,None,None,None,Routes to faq intent while keeping flow='booki...,None
200,tr-4881e2efb6267bd75f536cf0f1e0aa52,"{'user_message': 'Can I pay my bill online?', ...","=== INTENT ===\nfaq\n\n=== TOOLS ===\n[""search...",criteria,True,None,None,None,Routes to faq intent.,None
205,tr-4d878f1d290092d61e9a0ed97bef950d,{'user_message': 'What is the parking situatio...,"=== INTENT ===\nfaq\n\n=== TOOLS ===\n[""search...",criteria,True,None,None,None,Routes to faq intent.,None
210,tr-3e9f898c691228c051b8946fec9d7ed7,{'user_message': 'I want to change my primary ...,=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,criteria,True,None,None,None,Routes to escalation intent.,None
215,tr-c392bee41ef8bd7c152efee973348538,{'user_message': 'I'd like to book an appointm...,=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,criteria,True,None,None,None,Routes to booking intent.,None
220,tr-aa12a8cac390dd9625b24798c5265e13,"{'user_message': 'I lost my prescription.', 'c...",=== INTENT ===\nescalation\n\n=== TOOLS ===\n[...,criteria,True,None,None,None,Routes to escalation intent.,None
225,tr-e3cd1fa53ef400e875c23d4558ce2881,{'user_message': 'What are your clinic hours?'...,"=== INTENT ===\nfaq\n\n=== TOOLS ===\n[""search...",criteria,True,None,None,None,Routes to faq intent.,None
230,tr-1902961650d31b8d58d2a1fbdd342f50,{'user_message': 'I need to cancel my appointm...,=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,criteria,True,None,None,None,Routes to booking intent.,None
235,tr-6df53f787a6532119e207d72e55fd0c2,{'user_message': 'I want to complain about Dr....,=== INTENT ===\nescalation\n\n=== TOOLS ===\n[...,criteria,True,None,None,None,Routes to escalation intent.,None

In [27]:
row['assessments']

[{'assessment_id': 'a-8f43617c12fb442a97ae5360081ecb33',
  'assessment_name': 'ExpectationsMet',
  'trace_id': 'tr-6df53f787a6532119e207d72e55fd0c2',
  'span_id': 'dc6102b959144839',
  'source': {'source_type': 'LLM_JUDGE', 'source_id': 'openai:/gpt-4o-mini'},
  'create_time': '2026-07-25T00:53:57.524Z',
  'last_update_time': '2026-07-25T00:53:57.524Z',
  'feedback': {'value': 'no'},
  'rationale': 'The response does not clearly indicate a specific route to escalation, as it does not mention that the issue will be escalated or that it is being directed to the escalation team. Instead, it simply states that someone will contact the user, which could imply various levels of support without confirming that it is being escalated.',
  'metadata': {'mlflow.assessment.judgeCost': '9.915e-05',
   'guideline': '\n    You are evaluating whether an agent met specific expectations.\n    \n    Given the expectation criteria: {{ expectations }}\n    \n    Extract the text under the === RESPONSE === section from the output {{ outputs }}.\n    Determine if this response successfully fulfills the provided expectations.\n    \n    Return "yes" if the expectations are met, "no" if they are not.\n    ',
   'mlflow.assessment.judgeOutputTokens': '72',
   'mlflow.assessment.sourceRunId': '35819fe559ee4a5b9d1e091f8146c94b',
   'mlflow.assessment.judgeInputTokens': '373'},
  'valid': True},
 {'assessment_id': 'a-aca86ccf7fa346ceb5b3c74cb2e903f5',
  'assessment_name': 'Faithfulness',
  'trace_id': 'tr-6df53f787a6532119e207d72e55fd0c2',
  'span_id': 'dc6102b959144839',
  'source': {'source_type': 'LLM_JUDGE', 'source_id': 'openai:/gpt-4o-mini'},
  'create_time': '2026-07-25T00:53:57.584Z',
  'last_update_time': '2026-07-25T00:53:57.584Z',
  'feedback': {'value': 'no'},
  'rationale': 'The CONTEXT is empty (i.e., `""`), meaning there is no information provided to support the claims and statements in the RESPONSE. Therefore, the RESPONSE cannot be considered completely supported by the CONTEXT.',
  'metadata': {'mlflow.assessment.judgeCost': '8.999999999999999e-05',
   'guideline': '\n    You are evaluating whether an agent\'s response is faithful to the provided context.\n    \n    From the output {{ outputs }}, extract two sections:\n    1. The text under === CONTEXT ===\n    2. The text under === RESPONSE ===\n    \n    Determine if the information in the RESPONSE is completely supported by and grounded in the CONTEXT.\n    If the RESPONSE contains claims, facts, or data not present in the CONTEXT, return "no".\n    If the RESPONSE is entirely supported by the CONTEXT, return "yes".\n    ',
   'mlflow.assessment.judgeOutputTokens': '53',
   'mlflow.assessment.sourceRunId': '35819fe559ee4a5b9d1e091f8146c94b',
   'mlflow.assessment.judgeInputTokens': '388'},
  'valid': True},
 {'assessment_id': 'a-c8e2335394fb4e528b0cc16f32389304',
  'assessment_name': 'ResponseQuality',
  'trace_id': 'tr-6df53f787a6532119e207d72e55fd0c2',
  'span_id': 'dc6102b959144839',
  'source': {'source_type': 'LLM_JUDGE', 'source_id': 'openai:/gpt-4o-mini'},
  'create_time': '2026-07-25T00:54:00.295Z',
  'last_update_time': '2026-07-25T00:54:00.295Z',
  'feedback': {'value': 'yes'},
  'rationale': 'The response is clear and coherent, effectively communicating the need for personal attention and reassuring the user that someone will contact them. The tone is professional, maintaining a courteous and appreciative approach, which is suitable for customer service scenarios. Additionally, it is helpful to the user, addressing their need for assistance and setting an expectation for follow-up.',
  'metadata': {'mlflow.assessment.judgeCost': '9.974999999999999e-05',
   'guideline': '\n    You are evaluating the quality of an agent\'s response.\n    \n    Extract the text under the === RESPONSE === section from the output {{ outputs }}.\n    Evaluate the overall quality of this response based on:\n    1. Clarity and coherence\n    2. Professionalism and tone\n    3. Helpfulness to the user\n    \n    Return "yes" if the response is of high quality, "no" otherwise.\n    ',
   'mlflow.assessment.judgeOutputTokens': '75',
   'mlflow.assessment.sourceRunId': '35819fe559ee4a5b9d1e091f8146c94b',
   'mlflow.assessment.judgeInputTokens': '365'},
  'valid': True},
 {'assessment_id': 'a-a4b760cafe2d4bed88ca19c5dd09c201',
  'assessment_name': 'criteria',
  'trace_id': 'tr-6df53f787a6532119e207d72e55fd0c2',
  'span_id': 'dc6102b959144839',
  'source': {'source_type': 'HUMAN', 'source_id': 'phen'},
  'create_time': '2026-07-25T00:54:00.300Z',
  'last_update_time': '2026-07-25T00:54:00.300Z',
  'expectation': {'value': 'Routes to escalation intent.'},
  'metadata': {'mlflow.assessment.sourceRunId': '35819fe559ee4a5b9d1e091f8146c94b'},
  'valid': True},
 {'assessment_id': 'a-d35748e619c6484ea39b9d75231fd524',
  'assessment_name': 'expected_route',
  'trace_id': 'tr-6df53f787a6532119e207d72e55fd0c2',
  'span_id': 'dc6102b959144839',
  'source': {'source_type': 'HUMAN', 'source_id': 'phen'},
  'create_time': '2026-07-25T00:54:00.300Z',
  'last_update_time': '2026-07-25T00:54:00.300Z',
  'expectation': {'value': 'escalation'},
  'metadata': {'mlflow.assessment.sourceRunId': '35819fe559ee4a5b9d1e091f8146c94b'},
  'valid': True}]

In [23]:
if failed_traces:
    failed_df = pd.DataFrame(failed_traces)
    display(failed_df)
else:
    print("No failed traces to display.")

,trace_id,request,response,reasons,reasons_list
0,tr-64bfeb7e9224be6dffcaa339a9aed1d9,"{'user_message': 'I have a headache, what medi...",=== INTENT ===\nescalation\n\n=== TOOLS ===\n[...,"Faithfulness Failed: The CONTEXT is empty, pro...","[{'scorer_name': 'Faithfulness', 'error_reason..."
1,tr-1ea5370a2fb844d649e0d223ac46be2b,{'user_message': 'What should I do if my arm h...,=== INTENT ===\nescalation\n\n=== TOOLS ===\n[...,ExpectationsMet Failed: The response does not ...,"[{'scorer_name': 'ExpectationsMet', 'error_rea..."
2,tr-ca34320f35072d86109da83f05a616f4,{'user_message': 'Can I book an appointment fo...,=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,ExpectationsMet Failed: The response does not ...,"[{'scorer_name': 'ExpectationsMet', 'error_rea..."
3,tr-b6d1e906f83fa28b87870d536e70375d,{'user_message': 'How much does a dermatology ...,"=== INTENT ===\nfaq\n\n=== TOOLS ===\n[""search...",ExpectationsMet Failed: The response does not ...,"[{'scorer_name': 'ExpectationsMet', 'error_rea..."
4,tr-7d7a660d69ca8dc47bc4d76865e3a3fa,{'user_message': 'The 10am slot with Dr. Silva...,=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,ExpectationsMet Failed: The agent did not ask ...,"[{'scorer_name': 'ExpectationsMet', 'error_rea..."
5,tr-943f3e2dc62ff8c7e751a862e78bb219,{'user_message': 'Can I reschedule my appointm...,=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,ExpectationsMet Failed: The response does not ...,"[{'scorer_name': 'ExpectationsMet', 'error_rea..."
6,tr-b5fa726883ce28023b584ce73bcb6b29,{'user_message': '[System Event: Payment Expir...,=== INTENT ===\nescalation\n\n=== TOOLS ===\n[...,ExpectationsMet Failed: The response does not ...,"[{'scorer_name': 'ExpectationsMet', 'error_rea..."
7,tr-76b96b6342ab713aa946de49154ec572,"{'user_message': 'Yes, that's correct.', 'conv...",=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,ExpectationsMet Failed: The response does not ...,"[{'scorer_name': 'ExpectationsMet', 'error_rea..."
8,tr-1496b12efceaa9bed4e685388f617a4b,"{'user_message': 'I need an endocrinologist.',...",=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,"Faithfulness Failed: The CONTEXT is empty, mea...","[{'scorer_name': 'Faithfulness', 'error_reason..."
9,tr-c0a6294e652f23edb742847157d9a432,{'user_message': 'Do you have anything next Tu...,=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,ExpectationsMet Failed: The response did not c...,"[{'scorer_name': 'ExpectationsMet', 'error_rea..."
10,tr-78b19bcae9b58313d1337394292d06e5,{'user_message': 'I need to reschedule my Thur...,=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,ExpectationsMet Failed: The response does not ...,"[{'scorer_name': 'ExpectationsMet', 'error_rea..."
11,tr-ca7b36d19980877e0f8b1169e6caef46,{'user_message': 'I want to cancel my reservat...,=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,ExpectationsMet Failed: The response failed to...,"[{'scorer_name': 'ExpectationsMet', 'error_rea..."
12,tr-a41a953b4158022c3745efede3b3d91e,"{'user_message': 'Yes, please book it.', 'conv...",=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,ExpectationsMet Failed: The agent's response d...,"[{'scorer_name': 'ExpectationsMet', 'error_rea..."
13,tr-c65bdad9215445eb9e7606476489bcc6,{'user_message': 'Do you have any availability...,=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,ExpectationsMet Failed: The agent's response d...,"[{'scorer_name': 'ExpectationsMet', 'error_rea..."
14,tr-38ab56933e3e73237d892ca388622344,{'user_message': 'I want the 9am slot with Dr....,=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,ExpectationsMet Failed: The response does not ...,"[{'scorer_name': 'ExpectationsMet', 'error_rea..."
15,tr-10ff5c1dd64c8464cafcac9280a44077,{'user_message': '[System Event: Payment Confi...,=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,ExpectationsMet Failed: The response does not ...,"[{'scorer_name': 'ExpectationsMet', 'error_rea..."
16,tr-3b27012e509572089fe4563055f22d95,{'user_message': 'I need to cancel my appointm...,=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,"Faithfulness Failed: The CONTEXT is empty, whi...","[{'scorer_name': 'Faithfulness', 'error_reason..."
17,tr-b181330d66dbcc3ac372b5c5b5d6f2c1,{'user_message': 'The appointment is for my da...,=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,ExpectationsMet Failed: The response does not ...,"[{'scorer_name': 'ExpectationsMet', 'error_rea..."
18,tr-d38fc82df5003064364c83b4f2090a60,"{'user_message': 'My number is 555-9999, but I...","=== INTENT ===\nbooking\n\n=== TOOLS ===\n[""fi...",Faithfulness Failed: The RESPONSE contains inf...,"[{'scorer_name': 'Faithfulness', 'error_reason..."
19,tr-340c4aa9131465c26cf020a9a1631289,"{'user_message': 'Wait, I need to update my em...",=== INTENT ===\nescalation\n\n=== TOOLS ===\n[...,Faithfulness Failed: The CONTEXT provided does...,"[{'scorer_name': 'Faithfulness', 'error_reason..."
20,tr-8f1a48437362cf0f5a498f084c01368c,"{'user_message': 'Actually, my phone number is...",=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,Faithfulness Failed: The CONTEXT provided is a...,"[{'scorer_name': 'Faithfulness', 'error_reason..."
21,tr-d8d6498c64d3c997196c82ec4226601a,"{'user_message': 'Actually, can you book this ...","=== INTENT ===\nbooking\n\n=== TOOLS ===\n[""fi...",ExpectationsMet Failed: The response does not ...,"[{'scorer_name': 'ExpectationsMet', 'error_rea..."
22,tr-d73da6212fcd661a480ef511392713c0,{'user_message': 'My phone number is +15550001...,"=== INTENT ===\nbooking\n\n=== TOOLS ===\n[""fi...",Faithfulness Failed: The RESPONSE includes a c...,"[{'scorer_name': 'Faithfulness', 'error_reason..."
23,tr-1ee1c4ec934b7dbc80c6da02089b65b2,"{'user_message': 'It's for my son, Michael.', ...","=== INTENT ===\nbooking\n\n=== TOOLS ===\n[""fi...",ExpectationsMet Failed: The response does not ...,"[{'scorer_name': 'ExpectationsMet', 'error_rea..."
24,tr-9dc3fdf427eb449a5d4b567b2689e33f,{'user_message': 'I don't have a phone number....,=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,"Faithfulness Failed: The CONTEXT is empty, mea...","[{'scorer_name': 'Faithfulness', 'error_reason..."
25,tr-c557aa4f09d26229d17bb8654f2f8fe7,"{'user_message': 'I forgot my patient ID.', 'c...",=== INTENT ===\nescalation\n\n=== TOOLS ===\n[...,"Faithfulness Failed: The CONTEXT is empty, pro...","[{'scorer_name': 'Faithfulness', 'error_reason..."
26,tr-c7e177656754668be5943bbe3957e84d,"{'user_message': 'Hi.', 'conversation_history'...",=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,Faithfulness Failed: The CONTEXT section is em...,"[{'scorer_name': 'Faithfulness', 'error_reason..."
27,tr-4c3f46740884f1da63a8c04b9bc764ea,"{'user_message': 'My name is Jane Smith, +1444...","=== INTENT ===\nbooking\n\n=== TOOLS ===\n[""fi...",Faithfulness Failed: The RESPONSE includes a c...,"[{'scorer_name': 'Faithfulness', 'error_reason..."
28,tr-b2e57f242da990b34745523ce2fe937e,"{'user_message': 'Hi, I'd like to book an appo...",=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,"Faithfulness Failed: The CONTEXT is empty, whi...","[{'scorer_name': 'Faithfulness', 'error_reason..."
29,tr-195417a545abac6a9ba64d3985e3b2ac,{'user_message': 'This is ridiculous! I've bee...,=== INTENT ===\nescalation\n\n=== TOOLS ===\n[...,"Faithfulness Failed: The CONTEXT is empty, mea...","[{'scorer_name': 'Faithfulness', 'error_reason..."
30,tr-84fdb216699085e18edfa06489b875fb,"{'user_message': 'Where are you located?', 'co...","=== INTENT ===\nfaq\n\n=== TOOLS ===\n[""search...",Faithfulness Failed: The RESPONSE states that ...,"[{'scorer_name': 'Faithfulness', 'error_reason..."
31,tr-e2912f6141dfe9e3e8fcd2ca42f77e2d,{'user_message': 'Can I get my medical records...,"=== INTENT ===\nfaq\n\n=== TOOLS ===\n[""search...",ExpectationsMet Failed: The response does not ...,"[{'scorer_name': 'ExpectationsMet', 'error_rea..."
32,tr-c5ee6289b5a76e77a9f5b6c6a8d0d06f,"{'user_message': 'Cardiology.', 'conversation_...",=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,ExpectationsMet Failed: The response does not ...,"[{'scorer_name': 'ExpectationsMet', 'error_rea..."
33,tr-d0915f9247492f67948022fb8281d8d2,{'user_message': 'Who is the best doctor for b...,"=== INTENT ===\nfaq\n\n=== TOOLS ===\n[""search...",ExpectationsMet Failed: The response provided ...,"[{'scorer_name': 'ExpectationsMet', 'error_rea..."
34,tr-b6b48604c9ba50091031ec195632cf0d,"{'user_message': 'Actually, my phone number is...",=== INTENT ===\nescalation\n\n=== TOOLS ===\n[...,"Faithfulness Failed: The CONTEXT is empty, whi...","[{'scorer_name': 'Faithfulness', 'error_reason..."
35,tr-d20d3c24519db8a09f31eb3d1aad1013,{'user_message': 'Can I add a dependent to my ...,"=== INTENT ===\nfaq\n\n=== TOOLS ===\n[""search...",Faithfulness Failed: The RESPONSE claims that ...,"[{'scorer_name': 'Faithfulness', 'error_reason..."
36,tr-f22c6f58c35eb240cdd6a7bce976dbaf,"{'user_message': 'Actually, how much does a de...","=== INTENT ===\nfaq\n\n=== TOOLS ===\n[""search...",Faithfulness Failed: The RESPONSE states an in...,"[{'scorer_name': 'Faithfulness', 'error_reason..."
37,tr-4d878f1d290092d61e9a0ed97bef950d,{'user_message': 'What is the parking situatio...,"=== INTENT ===\nfaq\n\n=== TOOLS ===\n[""search...",ExpectationsMet Failed: The response provided ...,"[{'scorer_name': 'ExpectationsMet', 'error_rea..."
38,tr-3e9f898c691228c051b8946fec9d7ed7,{'user_message': 'I want to change my primary ...,=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,Faithfulness Failed: The CONTEXT is empty (it ...,"[{'scorer_name': 'Faithfulness', 'error_reason..."
39,tr-c392bee41ef8bd7c152efee973348538,{'user_message': 'I'd like to book an appointm...,=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,ExpectationsMet Failed: The response provided ...,"[{'scorer_name': 'ExpectationsMet', 'error_rea..."
40,tr-aa12a8cac390dd9625b24798c5265e13,"{'user_message': 'I lost my prescription.', 'c...",=== INTENT ===\nescalation\n\n=== TOOLS ===\n[...,ExpectationsMet Failed: The response does not ...,"[{'scorer_name': 'ExpectationsMet', 'error_rea..."
41,tr-1902961650d31b8d58d2a1fbdd342f50,{'user_message': 'I need to cancel my appointm...,=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n...,ExpectationsMet Failed: The response provided ...,"[{'scorer_name': 'ExpectationsMet', 'error_rea..."
42,tr-6df53f787a6532119e207d72e55fd0c2,{'user_message': 'I want to complain about Dr....,=== INTENT ===\nescalation\n\n=== TOOLS ===\n[...,ExpectationsMet Failed: The response does not ...,"[{'scorer_name': 'ExpectationsMet', 'error_rea..."

In [24]:
failed_df['n_reasons'] = failed_df['reasons'].apply(lambda x: len(x.split("|")) )

In [25]:
failed_df['reasons'].values

array(['Faithfulness Failed: The CONTEXT is empty, providing no specific information or details to support the RESPONSE. The RESPONSE contains a message suggesting that someone will contact the individual for assistance, which is not grounded in any context present.',
       'ExpectationsMet Failed: The response does not address medical advice or recommend consulting a doctor. It simply states that someone will contact the user for assistance, which does not fulfill the expectation criteria. | Faithfulness Failed: The CONTEXT is empty, which means there are no supporting facts, claims, or information provided. The RESPONSE, however, gives a specific message indicating that someone will contact the user for assistance. Since the RESPONSE contains information that is not grounded in any provided CONTEXT, it cannot be considered completely supported.',
       'ExpectationsMet Failed: The response does not directly handle the booking. Instead, it asks for additional information to retrieve the user\'s record, indicating that the agent is not processing the booking at that moment. | Faithfulness Failed: The CONTEXT is empty (indicated by ""), which means there is no information to support any claims or statements made in the RESPONSE. The RESPONSE asks for personal information and implies an action regarding a booking without any grounding in the provided CONTEXT.',
       "ExpectationsMet Failed: The response does not confirm the use of 'search_services_tool' as expected, even though the tool was listed in the available tools. The output indicates an error related to the tool's validity, suggesting that it was not actually called during the response generation. Therefore, the expectation of calling the 'search_services_tool' is not met. | Faithfulness Failed: The RESPONSE contains claims about the inability to provide pricing information and suggests searching for general information about dermatology consultations. However, the CONTEXT only provides information about an error related to the tool 'search_services_tool' not being valid and does not support the details mentioned in the RESPONSE. Therefore, the RESPONSE is not completely supported by the CONTEXT.",
       "ExpectationsMet Failed: The agent did not ask for explicit confirmation before calling the 'reserve_slot_tool', and there is no indication that the tool is even being considered in the response. In fact, no tools were listed in the output, which means the expectation of confirming before using the 'reserve_slot_tool' was not met. | Faithfulness Failed: The CONTEXT section is empty, which means there is no information to support or ground the RESPONSE provided. The RESPONSE makes inquiries regarding a user's registration which cannot be validated or referenced from the CONTEXT.",
       "ExpectationsMet Failed: The response does not use the 'reschedule_appointment_tool' as expected. The tool list is empty in the output, indicating that no tools were utilized for the response. | Faithfulness Failed: The CONTEXT is empty (i.e., there is no information provided), which means that the RESPONSE cannot be grounded in any prior context. Since the RESPONSE includes a request for personal information and assumes prior registration, it introduces claims not supported by the lack of context, leading to the conclusion that it is not fully supported.",
       'ExpectationsMet Failed: The response does not acknowledge that the payment expired or that the reservation was released. It fails to address the situation directly or ask if the customer wants to try booking again. Instead, it informs the user that someone will contact them, which does not fulfill the expectations. | Faithfulness Failed: The CONTEXT section is empty (i.e., it contains no information), while the RESPONSE includes a message about the need for personal attention from staff and an assurance that someone will contact the client. Since there is no context provided to support any part of the RESPONSE, the information cannot be considered grounded in the CONTEXT.',
       "ExpectationsMet Failed: The response does not call the 'reserve_slot_tool' as required by the expectations. In the TOOLS section, it shows that no tools were invoked (i.e., []), indicating that the tool expected was not utilized. | Faithfulness Failed: The CONTEXT is empty, containing no information, yet the RESPONSE assumes there is an existing registration system and asks for personal information. Since there is no supporting context for these claims or inquiries, the RESPONSE is not grounded in the CONTEXT.",
       "Faithfulness Failed: The CONTEXT is empty, meaning there is no information provided that can support or ground the RESPONSE. The questions about registration and personal information such as full name and phone number or email are not derived from any context given. | ExpectationsMet Failed: The agent did not call the 'check_availability_tool' as specified in the expectations. In the output, the 'TOOLS' section shows an empty list, indicating that no tools were used in the response. Therefore, the expectations were not met.",
       "ExpectationsMet Failed: The response did not call the 'check_availability_tool' as specified in the expectations. The tools section lists an empty array, indicating that no tools were invoked. | Faithfulness Failed: The CONTEXT is empty, which means there is no provided information to support the RESPONSE. The RESPONSE contains a question requesting personal information which has no basis in the CONTEXT. Therefore, the RESPONSE cannot be considered completely supported by the CONTEXT.",
       "ExpectationsMet Failed: The response does not utilize the 'reschedule_appointment_tool' as required by the expectations. It instead focuses on gathering personal information but does not demonstrate the use of the expected tool for rescheduling an appointment. | Faithfulness Failed: The CONTEXT is empty, which means there is no information provided to support any claims or actions in the RESPONSE. The RESPONSE asks for personal information, but since there is no context to support the need for this request or any related information, the RESPONSE is not grounded in the CONTEXT.",
       "ExpectationsMet Failed: The response failed to call either the 'cancel_appointment_tool' or 'cancel_reservation_tool', which are the expected tools according to the criteria. Instead, the response provides general assistance without attempting to cancel a reservation. | Faithfulness Failed: The CONTEXT does not provide any information regarding capabilities or actions, as it is an empty string. However, the RESPONSE implies that the agent can assist with cancellation and requires personal information to access records. This creates claims about functionality and user information that are not supported by the CONTEXT, which means the RESPONSE is not grounded in it.",
       "ExpectationsMet Failed: The agent's response does not meet the expectation of calling the 'reserve_slot_tool'. The tools used in the interaction are listed as an empty array, indicating that no tools were called, including the expected 'reserve_slot_tool'. | Faithfulness Failed: The CONTEXT is empty, which means there is no information provided to support the RESPONSE. The RESPONSE contains an implied question about registration and asks for personal information, neither of which is based on or grounded in any context. Therefore, it cannot be supported by the CONTEXT.",
       "ExpectationsMet Failed: The agent's response does not call the 'check_availability_tool' as required by the expectations. In fact, the tools section indicates that no tools were utilized. Additionally, there is no mention of the specialty being 'general' or 'checkup' or the use of a start_date for this Friday. Therefore, the response fails to meet the outlined criteria. | Faithfulness Failed: The CONTEXT is empty, meaning there are no instructions, prompts, or information from which the RESPONSE can be derived or supported. The RESPONSE contains a request for information (full name and phone number or email) that cannot directly relate back to an empty CONTEXT. Therefore, the claims made in the RESPONSE are not supported or grounded in the provided CONTEXT.",
       'ExpectationsMet Failed: The response does not ask for explicit confirmation of the 9am slot with Dr. Adams; instead, it inquires about the registrant\'s information without addressing the appointment time. | Faithfulness Failed: The CONTEXT provided is empty (""), meaning there is no information to support any claims or questions presented in the RESPONSE. The RESPONSE assumes knowledge of a registration process and asks for details that are not supported by any context, leading to the conclusion that the RESPONSE is not grounded in the CONTEXT.',
       "ExpectationsMet Failed: The response does not acknowledge payment as expected. Instead, it inquires about the user's registration without addressing any payment information. | Faithfulness Failed: The CONTEXT section contains an empty string, which means there is no information provided for the RESPONSE to be grounded in. The RESPONSE contains specific questions about registration and personal information that are not supported by any context. Therefore, the RESPONSE cannot be considered faithful to the CONTEXT.",
       "Faithfulness Failed: The CONTEXT is empty, which means there is no supporting information to validate the RESPONSE. The RESPONSE assumes the existence of user registration and requests personal information, neither of which is supported by any context provided. | ExpectationsMet Failed: The response did not call the 'cancel_appointment_tool' as expected. The tools section indicates an empty list, meaning no tools were utilized in the response.",
       "ExpectationsMet Failed: The response does not demonstrate that the agent has called the 'select_patient_tool' with Emma's patient_id. According to the expectations, the agent was required to invoke this specific tool, but the output shows that no tools were called ('TOOL' section is empty). Thus, the expectations are not met. | Faithfulness Failed: The CONTEXT is empty, meaning there is no information provided to support any claims made in the RESPONSE. The RESPONSE asks for personal information but without any context, it is unsupported. Thus, the RESPONSE is not grounded in any content.",
       'Faithfulness Failed: The RESPONSE contains information about not being able to find a record and offering to register the user, including a request for personal information. However, the CONTEXT only contains the output from the tool indicating that no data was found ("Tool find_contact_tool output: null\\n"). Since the CONTEXT does not support the claims made in the RESPONSE about registering the user or asking for personal details, the information in the RESPONSE is not fully supported by the CONTEXT.',
       'Faithfulness Failed: The CONTEXT provided does not contain any specific information or details, making it impossible for the RESPONSE to be fully supported or grounded in it. The RESPONSE includes claims about assistance and staff interaction that are not reflected or mentioned in the empty CONTEXT.',
       'Faithfulness Failed: The CONTEXT provided is an empty string, which means there is no information or details to support the claims made in the RESPONSE. The RESPONSE mentions needing to connect with staff members for data corrections, but since there is no corresponding context to validate this statement, it is not supported. | ResponseQuality Failed: The response is somewhat helpful in that it indicates that a staff member will reach out for data corrections. However, it lacks clarity regarding the specific nature of the data corrections, and there is no professional tone or warmth in the message. It could be improved by offering a clearer next step or providing more information about the timeframe and context for the follow-up. Therefore, it does not meet the criteria for high-quality response.',
       'ExpectationsMet Failed: The response does not effectively handle patient switching. Instead of indicating a switch for an existing patient or providing options related to switching between patients, it suggests registering Lucas as a new patient, indicating that the system did not recognize Lucas as an existing patient. This fails to meet the expectation of handling patient switching.',
       "Faithfulness Failed: The RESPONSE includes a claim about not being able to find a record with a phone number and asks for an email address and date of birth to register the user. However, the CONTEXT only states that the output of the 'find_contact_tool' is null, which does not directly imply that the agent is unable to find a record based on a phone number, nor does it mention asking for an email address or date of birth. Thus, some information in the RESPONSE is not directly supported by the CONTEXT.",
       "ExpectationsMet Failed: The response does not call the expected tool 'select_patient_tool', but instead references 'find_patient_tool'. This indicates that the expectation of invoking the correct tool with Michael's patient_id is not fulfilled.",
       'Faithfulness Failed: The CONTEXT is empty, meaning it does not provide any information to support the RESPONSE. Since the RESPONSE asks for personal information but lacks any related context, it cannot be considered supported or grounded. Therefore, the RESPONSE is not faithful to the CONTEXT.',
       'Faithfulness Failed: The CONTEXT is empty, providing no information to support the claims made in the RESPONSE. Therefore, the RESPONSE cannot be deemed as faithful to the CONTEXT. | ExpectationsMet Failed: The response does not proactively ask for any other identifiers such as full name and phone or email to do a lookup. It only acknowledges the request and indicates that someone will contact the user, without gathering any additional necessary information.',
       'Faithfulness Failed: The CONTEXT section is empty, which means there are no facts, claims, or data present to support the RESPONSE. The RESPONSE suggests actions and requests information without grounding those actions in the CONTEXT, making it unsupported.',
       "Faithfulness Failed: The RESPONSE includes a claim about not being able to find a record with the phone number, which is not explicitly stated in the CONTEXT. The CONTEXT only mentions the output of the tool as 'null', without specifying that this relates to a phone number or any other request, nor does it suggest the need for an email address and date of birth. Therefore, the RESPONSE contains information that is not fully supported by the CONTEXT.",
       'Faithfulness Failed: The CONTEXT is empty, which means there is no information to support the claims made in the RESPONSE. The RESPONSE contains a question about registration and personal information, which are not grounded in any provided context.',
       "Faithfulness Failed: The CONTEXT is empty, meaning there is no information provided to support the claims made in the RESPONSE. The RESPONSE contains specific claims about staff assistance and communication that are not grounded in any provided CONTEXT. | ExpectationsMet Failed: The response does not explicitly mention or indicate an 'escalation' route as outlined in the expectations. While it suggests that the matter requires personal attention and implies that the issue will be escalated to a staff member, it fails to directly reference an escalation intent or provide clarity on the escalation process.",
       "Faithfulness Failed: The RESPONSE states that the agent couldn't find information about the physical location of the clinic, which is not mentioned in the CONTEXT. The CONTEXT only provides information about specialties, opening hours, and online consultations, and does not include anything about the clinic's physical location. Therefore, this claim is unsupported by the CONTEXT. | ExpectationsMet Failed: The agent's response does not route to the expected 'faq' intent as specified in the expectations. While the intent classification indicated 'faq', the response itself does not provide any information or guidance related to FAQs, instead, it indicates an inability to find relevant information. This indicates a failure to meet the criteria specified. | ResponseQuality Failed: The response lacks clarity because it explicitly states that the information about the physical location is unavailable, without offering an alternative or additional information that could assist the user. The tone is polite but does not convey professionalism, as it seems to dismiss the user's query without demonstrating thoroughness. Overall, the response is not very helpful, as it fails to provide any relevant information or direct the user to potential resources that may help them find the physical location.",
       "ExpectationsMet Failed: The response does not indicate any routes toward escalation as it primarily focuses on the lack of information related to the user's request regarding medical records. Instead of steering towards an escalation path, it invites the user to ask something else or rephrase their request. Therefore, the expected route of 'escalation' is not fulfilled. | Faithfulness Failed: The RESPONSE mentions an inability to find information about getting medical records sent, which is not supported by the CONTEXT provided. The CONTEXT contains information about the clinic's specialties and doctors but does not include any details regarding medical records or related policies. Thus, the RESPONSE is not grounded in the CONTEXT. | ResponseQuality Failed: The response lacks clarity and does not directly address the user's likely needs regarding medical records. It indicates that the information was not found, which is acceptable, but does not provide any alternatives or additional resources that may be relevant. The tone is polite but may come off as dismissive due to the lack of actionable suggestions. Overall, the response does not fully meet the criteria for helpfulness, coherence, and professionalism.",
       "ExpectationsMet Failed: The response does not clearly indicate a route to booking intent. While the intent is identified as 'booking', the actual response provided does not facilitate or progress a booking process; instead, it asks for personal information without directing the user towards making a booking. | Faithfulness Failed: The CONTEXT provided is empty, containing just two double quotes with no information. However, the RESPONSE makes an assumption about the user being registered and asks for personal information (full name and phone number or email) to retrieve a record, which is not supported by any information in the CONTEXT. Therefore, the RESPONSE is not grounded in the CONTEXT.",
       "ExpectationsMet Failed: The response provided does not route directly to the 'faq' intent as required by the expectations. While it contains information related to clinic services, it does not explicitly refer or link to the FAQ section or indicate that it is addressing questions commonly asked by clients. The agent should have directly answered a frequently asked question or directed the user to the FAQ content.",
       'Faithfulness Failed: The CONTEXT is empty, which means there is no supporting information provided. The RESPONSE contains specific claims about someone contacting the user and a message of appreciation for patience, which are not grounded in any context provided. | ExpectationsMet Failed: The response does not explicitly route to an escalation process, despite mentioning personal attention from staff members. The language used is vague and does not clearly indicate that the issue is being escalated. It simply states that someone will contact the user without detailing the escalation route.',

In [26]:
failing_reasons_df = failed_df.explode('reasons_list')

In [27]:
all_failing_reasons = pd.concat((failing_reasons_df, failing_reasons_df.reasons_list.apply(pd.Series)), axis = 1)

In [28]:

all_failing_reasons['scorer_name'].value_counts()

scorer_name
Faithfulness       39
ExpectationsMet    33
ResponseQuality     5
Name: count, dtype: int64

In [29]:

all_failing_reasons['error_reason'].value_counts()

error_reason
no error rationale    77
Name: count, dtype: int64

In [41]:
all_failing_reasons['rationale'].value_counts().sort_values( ascending=False).to_frame()

                                                    count
rationale
The CONTEXT is empty, providing no specific inf...      1
The response does not address medical advice or...      1
The CONTEXT is empty, which means there are no ...      1
The response does not directly handle the booki...      1
The CONTEXT is empty (indicated by ""), which m...      1
...                                                   ...
The CONTEXT section is empty, which means there...      1
The response provided does not route to booking...      1
The CONTEXT provided is empty (""), which means...      1
The response does not clearly indicate a specif...      1
The CONTEXT is empty (i.e., `""`), meaning ther...      1

[77 rows x 1 columns]

In [46]:
all_failing_reasons[['trace_id','scorer_name','rationale']]

,trace_id,scorer_name,rationale
0,tr-64bfeb7e9224be6dffcaa339a9aed1d9,Faithfulness,"The CONTEXT is empty, providing no specific in..."
1,tr-1ea5370a2fb844d649e0d223ac46be2b,ExpectationsMet,The response does not address medical advice o...
1,tr-1ea5370a2fb844d649e0d223ac46be2b,Faithfulness,"The CONTEXT is empty, which means there are no..."
2,tr-ca34320f35072d86109da83f05a616f4,ExpectationsMet,The response does not directly handle the book...
2,tr-ca34320f35072d86109da83f05a616f4,Faithfulness,"The CONTEXT is empty (indicated by """"), which ..."
...,...,...,...
40,tr-aa12a8cac390dd9625b24798c5265e13,Faithfulness,"The CONTEXT section is empty, which means ther..."
41,tr-1902961650d31b8d58d2a1fbdd342f50,ExpectationsMet,The response provided does not route to bookin...
41,tr-1902961650d31b8d58d2a1fbdd342f50,Faithfulness,"The CONTEXT provided is empty (""""), which mean..."
42,tr-6df53f787a6532119e207d72e55fd0c2,ExpectationsMet,The response does not clearly indicate a speci...
42,tr-6df53f787a6532119e207d72e55fd0c2,Faithfulness,"The CONTEXT is empty (i.e., `""""`), meaning the..."

In [47]:
all_failing_reasons['expectation'].value_counts()

Series([], Name: count, dtype: int64)

----
---

In [44]:
failed_traces

[{'trace_id': 'tr-64bfeb7e9224be6dffcaa339a9aed1d9',
  'request': {'user_message': 'I have a headache, what medicine should I take?',
   'conversation_history': [],
   'agent_under_test': 'faq',
   'kwargs': {}},
  'response': '=== INTENT ===\nescalation\n\n=== TOOLS ===\n[]\n\n=== CONTEXT ===\n""\n\n=== RESPONSE ===\nThank you for reaching out. This requires personal attention from one of our staff members. Someone will contact you shortly to assist you directly. We appreciate your patience.\n',
  'reasons': 'Faithfulness Failed: The CONTEXT is empty, providing no specific information or details to support the RESPONSE. The RESPONSE contains a message suggesting that someone will contact the individual for assistance, which is not grounded in any context present.',
  'reasons_list': [{'scorer_name': 'Faithfulness',
    'error_reason': 'no error rationale',
    'rationale': 'The CONTEXT is empty, providing no specific information or details to support the RESPONSE. The RESPONSE contains a message suggesting that someone will contact the individual for assistance, which is not grounded in any context present.',
    'expectation': None}]},
 {'trace_id': 'tr-1ea5370a2fb844d649e0d223ac46be2b',
  'request': {'user_message': 'What should I do if my arm hurts?',
   'conversation_history': [],
   'agent_under_test': 'faq',
   'kwargs': {}},
  'response': '=== INTENT ===\nescalation\n\n=== TOOLS ===\n[]\n\n=== CONTEXT ===\n""\n\n=== RESPONSE ===\nThank you for reaching out. This requires personal attention from one of our staff members. Someone will contact you shortly to assist you directly. We appreciate your patience.\n',
  'reasons': 'ExpectationsMet Failed: The response does not address medical advice or recommend consulting a doctor. It simply states that someone will contact the user for assistance, which does not fulfill the expectation criteria. | Faithfulness Failed: The CONTEXT is empty, which means there are no supporting facts, claims, or information provided. The RESPONSE, however, gives a specific message indicating that someone will contact the user for assistance. Since the RESPONSE contains information that is not grounded in any provided CONTEXT, it cannot be considered completely supported.',
  'reasons_list': [{'scorer_name': 'ExpectationsMet',
    'error_reason': 'no error rationale',
    'rationale': 'The response does not address medical advice or recommend consulting a doctor. It simply states that someone will contact the user for assistance, which does not fulfill the expectation criteria.',
    'expectation': None},
   {'scorer_name': 'Faithfulness',
    'error_reason': 'no error rationale',
    'rationale': 'The CONTEXT is empty, which means there are no supporting facts, claims, or information provided. The RESPONSE, however, gives a specific message indicating that someone will contact the user for assistance. Since the RESPONSE contains information that is not grounded in any provided CONTEXT, it cannot be considered completely supported.',
    'expectation': None}]},
 {'trace_id': 'tr-ca34320f35072d86109da83f05a616f4',
  'request': {'user_message': 'Can I book an appointment for tomorrow?',
   'conversation_history': [],
   'agent_under_test': 'faq',
   'kwargs': {}},
  'response': '=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n\n=== CONTEXT ===\n""\n\n=== RESPONSE ===\nHello! Are you already registered with us? If so, could you share your full name and phone number (or email) so I can pull up your record?\n',
  'reasons': 'ExpectationsMet Failed: The response does not directly handle the booking. Instead, it asks for additional information to retrieve the user\'s record, indicating that the agent is not processing the booking at that moment. | Faithfulness Failed: The CONTEXT is empty (indicated by ""), which means there is no information to support any claims or statements made in the RESPONSE. The RESPONSE asks for personal information and implies an action regarding a booking without any grounding in the provided CONTEXT.',
  'reasons_list': [{'scorer_name': 'ExpectationsMet',
    'error_reason': 'no error rationale',
    'rationale': "The response does not directly handle the booking. Instead, it asks for additional information to retrieve the user's record, indicating that the agent is not processing the booking at that moment.",
    'expectation': None},
   {'scorer_name': 'Faithfulness',
    'error_reason': 'no error rationale',
    'rationale': 'The CONTEXT is empty (indicated by ""), which means there is no information to support any claims or statements made in the RESPONSE. The RESPONSE asks for personal information and implies an action regarding a booking without any grounding in the provided CONTEXT.',
    'expectation': None}]},
 {'trace_id': 'tr-b6d1e906f83fa28b87870d536e70375d',
  'request': {'user_message': 'How much does a dermatology consultation cost?',
   'conversation_history': [{'role': 'user',
     'content': 'I want to book a cardiology appointment.'},
    {'role': 'assistant',
     'content': 'Sure! Are you registered? Please share your name and phone number.'}],
   'agent_under_test': 'faq',
   'kwargs': {}},
  'response': '=== INTENT ===\nfaq\n\n=== TOOLS ===\n["search_services_tool"]\n\n=== CONTEXT ===\n"Tool search_services_tool output: Error: search_services_tool is not a valid tool, try one of [search_faq_tool].\\n"\n\n=== RESPONSE ===\nI apologize, but I am unable to provide pricing information directly. My tools do not have access to live service pricing. Would you like me to search for general information about dermatology consultations instead?\n',
  'reasons': "ExpectationsMet Failed: The response does not confirm the use of 'search_services_tool' as expected, even though the tool was listed in the available tools. The output indicates an error related to the tool's validity, suggesting that it was not actually called during the response generation. Therefore, the expectation of calling the 'search_services_tool' is not met. | Faithfulness Failed: The RESPONSE contains claims about the inability to provide pricing information and suggests searching for general information about dermatology consultations. However, the CONTEXT only provides information about an error related to the tool 'search_services_tool' not being valid and does not support the details mentioned in the RESPONSE. Therefore, the RESPONSE is not completely supported by the CONTEXT.",
  'reasons_list': [{'scorer_name': 'ExpectationsMet',
    'error_reason': 'no error rationale',
    'rationale': "The response does not confirm the use of 'search_services_tool' as expected, even though the tool was listed in the available tools. The output indicates an error related to the tool's validity, suggesting that it was not actually called during the response generation. Therefore, the expectation of calling the 'search_services_tool' is not met.",
    'expectation': None},
   {'scorer_name': 'Faithfulness',
    'error_reason': 'no error rationale',
    'rationale': "The RESPONSE contains claims about the inability to provide pricing information and suggests searching for general information about dermatology consultations. However, the CONTEXT only provides information about an error related to the tool 'search_services_tool' not being valid and does not support the details mentioned in the RESPONSE. Therefore, the RESPONSE is not completely supported by the CONTEXT.",
    'expectation': None}]},
 {'trace_id': 'tr-7d7a660d69ca8dc47bc4d76865e3a3fa',
  'request': {'user_message': 'The 10am slot with Dr. Silva works.',
   'conversation_history': [{'role': 'user',
     'content': 'Do you have anything next Tuesday with a cardiologist?'},
    {'role': 'assistant',
     'content': 'Here are the available cardiology slots for next Tuesday:\n- Dr. Silva at 10:00 AM\n- Dr. Silva at 14:30\n- Dr. Brooks at 11:00 AM'}],
   'agent_under_test': 'booking',
   'kwargs': {}},
  'response': '=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n\n=== CONTEXT ===\n""\n\n=== RESPONSE ===\nHello! Are you already registered with us? If so, could you share your full name and phone number (or email) so I can pull up your record?\n',
  'reasons': "ExpectationsMet Failed: The agent did not ask for explicit confirmation before calling the 'reserve_slot_tool', and there is no indication that the tool is even being considered in the response. In fact, no tools were listed in the output, which means the expectation of confirming before using the 'reserve_slot_tool' was not met. | Faithfulness Failed: The CONTEXT section is empty, which means there is no information to support or ground the RESPONSE provided. The RESPONSE makes inquiries regarding a user's registration which cannot be validated or referenced from the CONTEXT.",
  'reasons_list': [{'scorer_name': 'ExpectationsMet',
    'error_reason': 'no error rationale',
    'rationale': "The agent did not ask for explicit confirmation before calling the 'reserve_slot_tool', and there is no indication that the tool is even being considered in the response. In fact, no tools were listed in the output, which means the expectation of confirming before using the 'reserve_slot_tool' was not met.",
    'expectation': None},
   {'scorer_name': 'Faithfulness',
    'error_reason': 'no error rationale',
    'rationale': "The CONTEXT section is empty, which means there is no information to support or ground the RESPONSE provided. The RESPONSE makes inquiries regarding a user's registration which cannot be validated or referenced from the CONTEXT.",
    'expectation': None}]},
 {'trace_id': 'tr-943f3e2dc62ff8c7e751a862e78bb219',
  'request': {'user_message': 'Can I reschedule my appointment with Dr. Silva to tomorrow?',
   'conversation_history': [{'role': 'user',
     'content': 'Hi, +15550001234 (John Doe).'},
    {'role': 'assistant', 'content': 'Welcome back John! How can I help?'}],
   'agent_under_test': 'booking',
   'kwargs': {}},
  'response': '=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n\n=== CONTEXT ===\n""\n\n=== RESPONSE ===\nHello! Are you already registered with us? If so, could you share your full name and phone number (or email) so I can pull up your record?\n',
  'reasons': "ExpectationsMet Failed: The response does not use the 'reschedule_appointment_tool' as expected. The tool list is empty in the output, indicating that no tools were utilized for the response. | Faithfulness Failed: The CONTEXT is empty (i.e., there is no information provided), which means that the RESPONSE cannot be grounded in any prior context. Since the RESPONSE includes a request for personal information and assumes prior registration, it introduces claims not supported by the lack of context, leading to the conclusion that it is not fully supported.",
  'reasons_list': [{'scorer_name': 'ExpectationsMet',
    'error_reason': 'no error rationale',
    'rationale': "The response does not use the 'reschedule_appointment_tool' as expected. The tool list is empty in the output, indicating that no tools were utilized for the response.",
    'expectation': None},
   {'scorer_name': 'Faithfulness',
    'error_reason': 'no error rationale',
    'rationale': 'The CONTEXT is empty (i.e., there is no information provided), which means that the RESPONSE cannot be grounded in any prior context. Since the RESPONSE includes a request for personal information and assumes prior registration, it introduces claims not supported by the lack of context, leading to the conclusion that it is not fully supported.',
    'expectation': None}]},
 {'trace_id': 'tr-b5fa726883ce28023b584ce73bcb6b29',
  'request': {'user_message': '[System Event: Payment Expired]',
   'conversation_history': [{'role': 'user',
     'content': 'Yes, please book the 10am slot.'},
    {'role': 'assistant',
     'content': "I've reserved the 10:00 AM slot with Dr. Silva. A payment link will be generated shortly. The slot is held temporarily."}],
   'agent_under_test': 'booking',
   'kwargs': {}},
  'response': '=== INTENT ===\nescalation\n\n=== TOOLS ===\n[]\n\n=== CONTEXT ===\n""\n\n=== RESPONSE ===\nThank you for reaching out. This requires personal attention from one of our staff members. Someone will contact you shortly to assist you directly. We appreciate your patience.\n',
  'reasons': 'ExpectationsMet Failed: The response does not acknowledge that the payment expired or that the reservation was released. It fails to address the situation directly or ask if the customer wants to try booking again. Instead, it informs the user that someone will contact them, which does not fulfill the expectations. | Faithfulness Failed: The CONTEXT section is empty (i.e., it contains no information), while the RESPONSE includes a message about the need for personal attention from staff and an assurance that someone will contact the client. Since there is no context provided to support any part of the RESPONSE, the information cannot be considered grounded in the CONTEXT.',
  'reasons_list': [{'scorer_name': 'ExpectationsMet',
    'error_reason': 'no error rationale',
    'rationale': 'The response does not acknowledge that the payment expired or that the reservation was released. It fails to address the situation directly or ask if the customer wants to try booking again. Instead, it informs the user that someone will contact them, which does not fulfill the expectations.',
    'expectation': None},
   {'scorer_name': 'Faithfulness',
    'error_reason': 'no error rationale',
    'rationale': 'The CONTEXT section is empty (i.e., it contains no information), while the RESPONSE includes a message about the need for personal attention from staff and an assurance that someone will contact the client. Since there is no context provided to support any part of the RESPONSE, the information cannot be considered grounded in the CONTEXT.',
    'expectation': None}]},
 {'trace_id': 'tr-76b96b6342ab713aa946de49154ec572',
  'request': {'user_message': "Yes, that's correct.",
   'conversation_history': [{'role': 'user',
     'content': 'I want the 9am slot with Dr. Adams.'},
    {'role': 'assistant',
     'content': "To confirm — you'd like the 09:00 AM slot with Dr. Adams on Friday. Is that correct?"}],
   'agent_under_test': 'booking',
   'kwargs': {}},
  'response': '=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n\n=== CONTEXT ===\n""\n\n=== RESPONSE ===\nHello! Are you already registered with us? If so, could you share your full name and phone number (or email) so I can pull up your record?\n',
  'reasons': "ExpectationsMet Failed: The response does not call the 'reserve_slot_tool' as required by the expectations. In the TOOLS section, it shows that no tools were invoked (i.e., []), indicating that the tool expected was not utilized. | Faithfulness Failed: The CONTEXT is empty, containing no information, yet the RESPONSE assumes there is an existing registration system and asks for personal information. Since there is no supporting context for these claims or inquiries, the RESPONSE is not grounded in the CONTEXT.",
  'reasons_list': [{'scorer_name': 'ExpectationsMet',
    'error_reason': 'no error rationale',
    'rationale': "The response does not call the 'reserve_slot_tool' as required by the expectations. In the TOOLS section, it shows that no tools were invoked (i.e., []), indicating that the tool expected was not utilized.",
    'expectation': None},
   {'scorer_name': 'Faithfulness',
    'error_reason': 'no error rationale',
    'rationale': 'The CONTEXT is empty, containing no information, yet the RESPONSE assumes there is an existing registration system and asks for personal information. Since there is no supporting context for these claims or inquiries, the RESPONSE is not grounded in the CONTEXT.',
    'expectation': None}]},
 {'trace_id': 'tr-1496b12efceaa9bed4e685388f617a4b',
  'request': {'user_message': 'I need an endocrinologist.',
   'conversation_history': [{'role': 'user',
     'content': 'Hi, my phone is +15550001234 (John Doe).'},
    {'role': 'assistant',
     'content': 'Welcome back John! How can I help you today?'}],
   'agent_under_test': 'booking',
   'kwargs': {}},
  'response': '=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n\n=== CONTEXT ===\n""\n\n=== RESPONSE ===\nHello! Are you already registered with us? If so, could you share your full name and phone number (or email) so I can pull up your record?\n',
  'reasons': "Faithfulness Failed: The CONTEXT is empty, meaning there is no information provided that can support or ground the RESPONSE. The questions about registration and personal information such as full name and phone number or email are not derived from any context given. | ExpectationsMet Failed: The agent did not call the 'check_availability_tool' as specified in the expectations. In the output, the 'TOOLS' section shows an empty list, indicating that no tools were used in the response. Therefore, the expectations were not met.",
  'reasons_list': [{'scorer_name': 'Faithfulness',
    'error_reason': 'no error rationale',
    'rationale': 'The CONTEXT is empty, meaning there is no information provided that can support or ground the RESPONSE. The questions about registration and personal information such as full name and phone number or email are not derived from any context given.',
    'expectation': None},
   {'scorer_name': 'ExpectationsMet',
    'error_reason': 'no error rationale',
    'rationale': "The agent did not call the 'check_availability_tool' as specified in the expectations. In the output, the 'TOOLS' section shows an empty list, indicating that no tools were used in the response. Therefore, the expectations were not met.",
    'expectation': None}]},
 {'trace_id': 'tr-c0a6294e652f23edb742847157d9a432',
  'request': {'user_message': 'Do you have anything next Tuesday with a cardiologist?',
   'conversation_history': [{'role': 'user',
     'content': 'Hi, my phone is +15550001234.'},
    {'role': 'assistant',
     'content': "Welcome back, John! I've selected you as the patient. How can I help you today?"}],
   'agent_under_test': 'booking',
   'kwargs': {}},
  'response': '=== INTENT ===\nbooking\n\n=== TOOLS ===\n[]\n\n=== CONTEXT ===\n""\n\n=== RESPONSE ===\nHello! Are you already registered with us? If so, could you share your full name and phone number (or email) so I can pull up your record?\n',
  'reasons': "ExpectationsMet Failed: The response did not call the 'check_availability_tool' as specified in the expectations. The tools section lists an empty array, indicating that no tools were invoked. | Faithfulness Failed: The CONTEXT is empty, which means there is no provided information to support the RESPONSE. The RESPONSE contains a question requesting personal information which has no basis in the CONTEXT. Therefore, the RESPONSE cannot be considered completely supported by the CONTEXT.",
  'reasons_list': [{'scorer_name': 'ExpectationsMet',
    'error_reason': 'no error rationale',
    'rationale': "The response did not call the 'check_availability_tool' as specified in the expectations. The tools section lists an empty array, indicating that no tools were invoked.",
    'expectation': None},
   {'scorer_name': 'Faithfulness',
    'error_reason': 'no error rationale',
    'rationale': 'The CONTEXT is empty, which means there is no provided information to support the RESPONSE. The RESPONSE contains a question requesting personal information which has no basis in the CONTEXT. Therefore, the RESPONSE cannot be considered completely supported by the CONTEXT.',
    'expectation': None}]},
 {'trace_id': 'tr-78b19bcae9b58313d1337394292d06e5',
  'request': {'user_message': 'I need to reschedule my Thursday appointment to next week.',
   'conversation_history': [{'role': 'user',
     'content': 'Hi, +15550001234 (John Doe).'},
    {'role': 'assistant', 'content': 'Welcome back John! How can I help?'}],
   'agent_under_test': 'booking',
   'kwargs': {}},

In [15]:
from IPython.display import display

if failed_traces:
    # Display the full interactive trace for the first failed trace
    first_failed_trace_id = failed_traces[0]['trace_id']
    print(f"\nDisplaying full interactive trace for Trace ID: {first_failed_trace_id}")
    
    try:
        trace_obj = client.get_trace(first_failed_trace_id)
        display(trace_obj)
    except Exception as e:
        print(f"Could not fetch trace {first_failed_trace_id} from DB: {e}")

Displaying full interactive trace for Trace ID: tr-cda9fc6533486aa22c7962fbc1af85fb

Trace(trace_id=tr-cda9fc6533486aa22c7962fbc1af85fb)

In [ ]:
import mlflow

mlflow.set_tracking_uri("sqlite:///evaluation/mlflow.db")

# Replace with the actual Run ID printed in your terminal
run_id = "YOUR_RUN_ID" 

# This loads the exact same table you see in the CSV directly from MLflow!
df = mlflow.load_table(
    "eval_results", 
    run_ids=[run_id]
)

print(df.head())